# Generated by Django 4.1.4 on 2022-12-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_batteryType', models.CharField(max_length=50, null=True)),
                ('platform_batteryGeneration', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_company', models.CharField(max_length=50, null=True)),
                ('platform_model', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformFirmwareUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_navFirmwareUpgradeDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_serial', models.CharField(max_length=6, null=True)),
                ('platform_name', models.CharField(max_length=20, null=True)),
                ('platform_wmo', models.IntegerField(null=True)),
                ('platform_companyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformcompany')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformNavigationFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_navFirmwareVersion', models.CharField(max_length=20, null=True)),
                ('platform_navFirmwareComments', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_payloadSerialNumber', models.CharField(max_length=10, null=True)),
                ('platform_payloadOriginalPlatform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformname')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPayloadFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_payloadFirmwareVersion', models.CharField(max_length=20, null=True)),
                ('platform_payloadFirmwareVersionComments', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_releaseType', models.CharField(max_length=20, null=True)),
                ('platform_releaseAttachMethod', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPayloadFirmwareUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_payloadFirmwareUpgradeDate', models.DateField(null=True)),
                ('platform_payload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformpayload')),
                ('platform_payloadFirmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformpayloadfirmware')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_missionBattery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformbattery')),
                ('platform_missionFirmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformfirmwareupgrade')),
                ('platform_missionPayloadFirmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformpayloadfirmwareupgrade')),
                ('platform_missionRelease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformrelease')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_maintenanceDate', models.DateField(null=True)),
                ('platform_maintenanceComments', models.CharField(max_length=200, null=True)),
                ('platform_nameId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformname')),
            ],
        ),
        migrations.AddField(
            model_name='platformfirmwareupgrade',
            name='platform_maintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformmaintenance'),
        ),
        migrations.AddField(
            model_name='platformfirmwareupgrade',
            name='platform_navFirmware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformnavigationfirmware'),
        ),
    ]
