# Generated by Django 4.1.4 on 2022-12-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0002_instrumentcalibration_instrumentmake_instrumentmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformmission',
            name='platform_missionBattery',
        ),
        migrations.RemoveField(
            model_name='platformmission',
            name='platform_missionFirmware',
        ),
        migrations.RemoveField(
            model_name='platformmission',
            name='platform_missionPayloadFirmware',
        ),
        migrations.RemoveField(
            model_name='platformmission',
            name='platform_missionRelease',
        ),
        migrations.RemoveField(
            model_name='platformpayloadfirmwareupgrade',
            name='platform_payload',
        ),
        migrations.RemoveField(
            model_name='platformpayloadfirmwareupgrade',
            name='platform_payloadFirmware',
        ),
        migrations.DeleteModel(
            name='PlatformFirmwareUpgrade',
        ),
        migrations.DeleteModel(
            name='PlatformMission',
        ),
        migrations.DeleteModel(
            name='PlatformPayloadFirmwareUpgrade',
        ),
    ]
