# Generated by Django 4.1.4 on 2022-12-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0003_remove_platformmission_platform_missionbattery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_lastName', models.CharField(max_length=50)),
                ('contributor_firstName', models.CharField(max_length=50)),
                ('contributor_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='instrumentcalibration',
            name='instrument_calibrationDateNotes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrumentcalibration',
            name='instrument_calibrationReportNotes',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
