# Generated by Django 4.1.4 on 2022-12-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0004_contributorpeople_contributorrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgosTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argosTag_PTT', models.CharField(max_length=20)),
                ('argosTag_serialNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('institute_agency', models.CharField(max_length=100)),
                ('institute_city', models.CharField(max_length=50)),
                ('institute_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=50)),
            ],
        ),
    ]
