# Generated by Django 4.1 on 2023-01-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0005_argostag_institute_vessel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argostag',
            name='argosTag_serialNumber',
            field=models.CharField(max_length=10),
        ),
    ]
