# Generated by Django 4.1 on 2023-03-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0006_alter_argostag_argostag_serialnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgosTagPTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argosTag_PTT', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArgosTagSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argosTag_serialNumber', models.CharField(max_length=10)),
                ('argosTag_PTTNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.argostagptt')),
            ],
        ),
        migrations.DeleteModel(
            name='ArgosTag',
        ),
    ]
