# Generated by Django 4.1 on 2023-05-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0007_argostagptt_argostagserialnumber_delete_argostag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_number', models.IntegerField()),
                ('mission_cruiseNumber', models.CharField(max_length=20)),
                ('mission_deploymentDate', models.DateField(null=True)),
                ('mission_recoveryDate', models.DateField(null=True)),
                ('mission_batteryMax', models.DecimalField(decimal_places=1, max_digits=3)),
                ('mission_batteryMin', models.DecimalField(decimal_places=1, max_digits=3)),
                ('mission_deploymentLongitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mission_deploymentLatitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mission_recoveryLongitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mission_recoveryLatitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mission_minimumLongitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mission_minimumLatitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mission_maximumLongitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mission_maximumLatitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mission_waypointsGiven', models.CharField(max_length=100)),
                ('mission_distanceTravelled', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mission_numberOfYos', models.IntegerField()),
                ('mission_numberOfScienceYos', models.IntegerField()),
                ('mission_profilingScheme', models.CharField(max_length=10)),
                ('mission_numberOfAlarms', models.IntegerField()),
                ('mission_numberOfAlarmsWithOT', models.IntegerField()),
                ('mission_hoursOfOT', models.IntegerField()),
                ('mission_ballastedDensity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mission_comments', models.CharField(max_length=200)),
                ('mission_argosTag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.argostagserialnumber')),
                ('mission_deploymentVessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploymentVessel', to='gliderMetadataApp.vessel')),
                ('mission_institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.institute')),
                ('mission_platformBattery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformbattery')),
                ('mission_platformName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformname')),
                ('mission_platformNavFirmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformnavigationfirmware')),
                ('mission_platformPayload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformpayload')),
                ('mission_platformPayloadFirmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformpayloadfirmware')),
                ('mission_platformRelease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.platformrelease')),
                ('mission_recoveryVessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoveryVessel', to='gliderMetadataApp.vessel')),
            ],
        ),
    ]
