# Generated by Django 4.1 on 2023-07-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0009_instrumentmission_instrument_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_maximumLatitude',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_maximumLongitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_minimumLatitude',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_minimumLongitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_recoveryLatitude',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_recoveryLongitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
    ]
