# Generated by Django 4.1 on 2023-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0010_alter_mission_mission_maximumlatitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_numberOfAlarms',
            field=models.CharField(max_length=5),
        ),
    ]
