# Generated by Django 4.1 on 2023-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0011_alter_mission_mission_numberofalarms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_comments',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_numberOfScienceYos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_profilingScheme',
            field=models.CharField(max_length=20),
        ),
    ]
