# Generated by Django 4.1 on 2023-07-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0013_vocabulary_variablecfstandard_platformvariable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorrole',
            name='contributor_vocabulary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.vocabulary'),
        ),
    ]
