# Generated by Django 4.1 on 2023-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0014_contributorrole_contributor_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='vocabulary_notes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
