# Generated by Django 4.1 on 2023-07-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0015_vocabulary_vocabulary_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='vocabulary_notes',
            new_name='vocabulary_note',
        ),
    ]
