# Generated by Django 4.1 on 2023-07-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0016_rename_vocabulary_notes_vocabulary_vocabulary_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='vocabulary',
            new_name='vocabulary_name',
        ),
    ]
