# Generated by Django 4.1 on 2023-07-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0017_rename_vocabulary_vocabulary_vocabulary_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.mission')),
                ('contributor_missionPerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.contributorpeople')),
                ('contributor_missionRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.contributorrole')),
            ],
        ),
    ]
