# Generated by Django 4.1 on 2023-08-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0019_mission_mission_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCFStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_unit', models.CharField(max_length=25)),
                ('variable_nameVocabulary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='UnitNERCStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_unitUrn', models.CharField(max_length=50)),
                ('variable_unitUri', models.CharField(max_length=100)),
                ('variable_nameVocabulary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.vocabulary')),
            ],
        ),
        migrations.RemoveField(
            model_name='instrumentvariable',
            name='instrument_variableStandardCF',
        ),
        migrations.RemoveField(
            model_name='platformvariable',
            name='platform_variableStandardCF',
        ),
        migrations.RemoveField(
            model_name='variablecfstandard',
            name='variable_longName',
        ),
        migrations.RemoveField(
            model_name='variablecfstandard',
            name='variable_units',
        ),
        migrations.CreateModel(
            name='VariableNERCStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_standardNameUrn', models.CharField(max_length=100)),
                ('variable_standardNameUri', models.CharField(max_length=100)),
                ('variable_nameVocabulary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_parameterName', models.CharField(max_length=50)),
                ('variable_longName', models.CharField(max_length=75)),
                ('variable_parameterNameComment', models.CharField(max_length=50, null=True)),
                ('variable_cfName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.variablecfstandard')),
                ('variable_cfUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.unitcfstandard')),
                ('variable_nercName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.variablenercstandard')),
                ('variable_nercUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.unitnercstandard')),
            ],
        ),
        migrations.AddField(
            model_name='instrumentvariable',
            name='instrument_variableStandardName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.variable'),
        ),
        migrations.AddField(
            model_name='platformvariable',
            name='platform_variableStandardName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.variable'),
        ),
    ]
