# Generated by Django 4.1 on 2024-07-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0020_unitcfstandard_unitnercstandard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentSeabird43FOxygenCalibrationCoefficients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrationSeaBird43F_Soc', models.DecimalField(decimal_places=8, max_digits=10)),
                ('calibrationSeaBird43F_Foffset', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calibrationSeaBird43F_Tau20', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calibrationSeaBird43F_A', models.DecimalField(decimal_places=5, max_digits=7)),
                ('calibrationSeaBird43F_B', models.DecimalField(decimal_places=6, max_digits=8)),
                ('calibrationSeaBird43F_C', models.DecimalField(decimal_places=10, max_digits=12)),
                ('calibrationSeaBird43F_Enom', models.DecimalField(decimal_places=3, max_digits=5)),
                ('calibrationSeabird43F_calibration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.instrumentcalibration')),
            ],
        ),
    ]
