# Generated by Django 4.1 on 2024-07-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0021_instrumentseabird43foxygencalibrationcoefficients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentseabird43foxygencalibrationcoefficients',
            old_name='calibrationSeabird43F_calibration',
            new_name='calibrationSeaBird43F_calibration',
        ),
    ]
