# Generated by Django 4.1 on 2024-07-31 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0024_remove_instrumentvariable_instrument_variablestandardname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformvariable',
            name='platform_variableStandardName',
        ),
        migrations.AddField(
            model_name='platformvariable',
            name='platform_cfVariable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.variablecfstandard'),
        ),
        migrations.AddField(
            model_name='platformvariable',
            name='platform_nercVariable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.variablenercstandard'),
        ),
    ]
