# Generated by Django 4.1 on 2024-08-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0026_mission_mission_contributinginstitutionvocabulary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_network',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
