# Generated by Django 4.1 on 2024-08-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0029_instrumentvariable_instrument_gmcdkeyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentvariable',
            old_name='instrument_gmcdKeyword',
            new_name='instrument_gcmdKeyword',
        ),
    ]
