# Generated by Django 4.1 on 2024-08-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0030_rename_instrument_gmcdkeyword_instrumentvariable_instrument_gcmdkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_vocabulary', models.CharField(max_length=200)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='institute',
            name='institute_agency',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='institute_city',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='institute_country',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_contributingInstitutionVocabulary',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_contributingInstitutions',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_contributingInstitutionsRole',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='mission_contributingInstitutionsRoleVocabulary',
        ),
        migrations.AddField(
            model_name='institute',
            name='institute_vocabulary',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContributingInstitutionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributingInstitution_mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.mission')),
                ('contributingInstitution_missionInstitute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.institute')),
                ('contributingInstitution_missionRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.role')),
            ],
        ),
        migrations.AlterField(
            model_name='contributormission',
            name='contributor_missionRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gliderMetadataApp.role'),
        ),
        migrations.DeleteModel(
            name='ContributorRole',
        ),
    ]
