# Generated by Django 4.1 on 2024-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0031_role_remove_institute_institute_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_project',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
