# Generated by Django 4.1 on 2024-10-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0032_mission_mission_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentvariable',
            name='instrument_accuracy',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='instrumentvariable',
            name='instrument_precision',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='instrumentvariable',
            name='instrument_resolution',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='instrumentvariable',
            name='instrument_validMax',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='instrumentvariable',
            name='instrument_validMin',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
