# Generated by Django 5.1.4 on 2024-12-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0034_alter_instrumentvariable_instrument_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_comments',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
