# Generated by Django 5.1.4 on 2025-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0035_alter_mission_mission_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentmake',
            name='instrument_vocabulary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrumentmodel',
            name='instrument_vocabulary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='instrument_vocabulary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
