# Generated by Django 5.1.4 on 2025-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0036_instrumentmake_instrument_vocabulary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_ballastedDensity',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_batteryMax',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_batteryMin',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_deploymentLatitude',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_deploymentLongitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_distanceTravelled',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_hoursOfOT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_numberOfAlarms',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_numberOfAlarmsWithOT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_numberOfScienceYos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_numberOfYos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_profilingScheme',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_waypointsGiven',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
