# Generated by Django 5.1.4 on 2026-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0037_alter_mission_mission_ballasteddensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformname',
            name='platform_ices',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
