# Generated by Django 5.1.4 on 2026-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gliderMetadataApp', '0038_platformname_platform_ices'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
